Move to Cilium Only
giantswarm/k8s-dns-node-cache-app pull request #27
Opened 2023-01-20 11:32 UTC by paurosello

2023-01-21 08:01 UTC, whites11 requested changes
Lacks changelog entry

2023-01-31 10:02 UTC, whites11 approved these changes

2023-01-31 10:13 UTC, T-Kukawka commented on README.md
> +Release v2.x works in cilium mode only.
yes - let's be more clear on that please

2023-02-01 11:47 UTC, paurosello commented
I will leave basic-integration-test broken

2023-02-02 10:28 UTC, T-Kukawka approved these changes

2023-02-02 11:35 UTC, merged